---
- hosts: all
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
   - name: list
     raw: ls -la /var > /home/ansible/var.log
     run_once: true
     delegate_to: localhost
